const WordNet = require("node-wordnet");
const parse = require("csv-parse");
var natural = require("natural");
const npl = require("compromise");
const wordnet = new WordNet();
const tokenizer = new natural.WordTokenizer();

/* wordnet.lookup("bearing", function(results) {
  results.forEach(function(result) {
    console.log("------------------------------------");
    console.log("Id: ", result.synsetOffset);
    console.log("Part of Speech: ", result.pos);
    // n: noun, a: adjective, s: adjective (satellite), v: verb, r: adverb
    // adjective satellite is something Wordnet came up with - it refers to adjectives that always occur in instances relating to some other object - the canonical example is "atomic bomb"
    console.log("Lemma: ", result.lemma);
    console.log("Synonyms: ", result.synonyms);
    console.log("Description: ", result.gloss);
  });
}); */

var lexicon = {
  bearing: "Noun"
};

strings = [
  "ACTUATOR-BRK",
  "FLANG-SPLIT",
  "O-RING",
  "BOLT,M6X25MM HF",
  "BOLT,M6-1.0",
  "SCREW.CAP 444 44.4 ff.",
  "SCREW.CAP 444",
  "SCREW;CAP",
  "BOLT,M6-1.0",
  "screw and washer assembly (sems)",
  "screw",
  "angular contact (rolling) bearing",
  "Thrust bearings",
  "Thrust bear.",
  "Tensioner bearing",
  "screw,cap ff",
  "END bearing, ddfdfdf",
  "Tapped base bearing",
  "Load bearing element 1",
  "end bracket, testing",
  "Hanger bearings",
  "Flanged bearings",
  "screw,cap",
  "Angular contact bearing",
  "double-row (rolling) bearing",
  "screw,cap",
  "end bracket, bearing bracket (US)",
  "external-aligning (rolling) bearing",
  "filling slot (ball) bearing",
  "screw,cap",
  "#2 Heating fuel oil",
  "#4 or #6 Residual heavy fuel oils",
  "Aluminum SAE 6000 series hot rolled coil",
  "Aluminum, Reroll, Capacitor Foil Alloy 1145",
  "Aluminum, Sheet, Coiled Coated, Except Conductor & Decorative For Stamping",
  "700-R NEMA sealed industrial control relay",
  "802R NEMA 13 sealed contact",
  "802XR NEMA 7/9 hazardous location sealed contact",
  "Diaphragm seals",
  "Die cut seal kit",
  "MOTOR          STARTER",
  "V ring seal",
  "lip seal",
  "rotary shaft lip-type seal",
  "rubber-covered rotary shaft lip-type seal",
  "seal, O-ring",
  "seal kit",
  "motor with standardized mounting dimensions",
  "Connector to screw",
  "Earthing lug for cable screw gland",
  "Orthodontic expansion screws",
  "Self drilling tapping screw",
  "screw assembly",
  "BOLT,M6-1.0",
  "BOLT,HEX METRIC M6",
  "BOLT M6X25MM",
  "BOLT,M6X25MM HF",
  "NUT HEX FLG M6 1.0",
  "NUT HEX LOCK M6X1.0.00",
  "NUT,JAM,M6-1",
  "SCREW;CAP",
  "MOUNT,CALIBER,50,M6",
  "COVER",
  "BRACKET",
  "BRACKET",
  "RING-SNAP",
  "RETAINER",
  "SPRING",
  "HOUSING",
  "WAGNER PART",
  "WAGNER PART",
  "RING",
  "GEAR",
  "HEAD",
  "WIPER",
  "SEAL",
  "PISTON SYS",
  "O-RING-VITON",
  "WAGNER PART",
  "SHIM",
  "SPRING",
  "CAGE",
  "ROD",
  "ELEMENT",
  "ELEMENT",
  "SPRING",
  "PLATE",
  "DIAPHRAGM",
  "SUPPORT      -UPPER",
  "SEAL",
  "VALVE",
  "VALVE",
  "PLATE",
  "RING",
  "LOCK",
  "FLANG-SPLIT",
  "LOCKWASHER",
  "CAPSCREW",
  "HOSE",
  "HOSE ASSEMBLY",
  "WASHER",
  "HOUSING",
  "BEARING",
  "DIODE ASSY",
  "BRUSH ASSY",
  "PLATE",
  "BOARD",
  "CABLE ASSY",
  "CABLE ASSY",
  "LOCKWASHER",
  "NUT",
  "SCREW",
  "BUSHING",
  "BUSHING",
  "STUD",
  "BOLT",
  "BOLT",
  "CYLINDER",
  "CYLINDER",
  "WAGNER PART",
  "BUSHING",
  "RETAINING RING",
  "SCREW",
  "WAGNER PART",
  "CLAMP",
  "CLAMP",
  "PLATE",
  "BOLT",
  "SPRING",
  "WAGNER PART",
  "PLUG",
  "SPR BOOSTER",
  "FLANGE SCREW",
  "DIAPHRAGM",
  "O-RING",
  "CAP",
  "CAP",
  "BAFFLE PLATE",
  "BAFFLE PLATE",
  "CLAMP, HOSE",
  "SPRING",
  "BOOT",
  "SWITCH",
  "SWITCH",
  "HOSE ASSY",
  "PISTON",
  "SCREW",
  "ROTOR",
  "WAGNER PART",
  "WAGNER PART",
  "WAGNER PART",
  "DIODE",
  "DIODE",
  "DIODE",
  "DIODE",
  "DIODE",
  "FIELD COIL",
  "SCREW",
  "SCREW",
  "SCREW",
  "SCREW",
  "BUSHING",
  "BUSHING",
  "INSULATOR",
  "WAGNER PART",
  "COVER",
  "VALVE",
  "VALVE",
  "VALVE",
  "SEAL",
  "WAGNER PART",
  "CONE-ROLLER",
  "SWITCH",
  "SWITCH",
  "WAGNER PART",
  "SPIDER ASSY",
  "GEAR",
  "WAGNER PART",
  "WAGNER PART",
  "SEAL",
  "MODULAR BRG",
  "SEAL",
  "MOD. KIT",
  "SEAL",
  "KIT",
  "PIN LOCK",
  "CLAMP",
  "CLAMP",
  "CARRIER ASSY",
  "STUD         -RETAINER",
  "GEAR HUB",
  "SEAL",
  "CAGE-RETAIN",
  "KIT-BRG",
  "WAGNER PART",
  "WAGNER PART",
  "WAGNER PART",
  "GEAR",
  "DIFFERENT.GEAR",
  "DIFF.KIT",
  "GEAR",
  "SPRING",
  "RETAINER",
  "BRAKE",
  "RING",
  "RING",
  "RING",
  "O-RING",
  "O-RING",
  "SEAL",
  "SEAL",
  "PISTON",
  "SWIVEL",
  "HOUSING ASSY",
  "STARTER",
  "WAGNER PART",
  "ROTOR ASSY",
  "HOUSING",
  "HOUSING",
  "BEARING-RLR",
  "DRIVE ASSY",
  "REGULATOR",
  "LIGHT",
  "LIGHT",
  "STUD",
  "STUD",
  "STUD",
  "GASKET",
  "LOCKWASHER",
  "CABLE",
  "CABLE",
  "CABLE",
  "CAPSCREW",
  "SEAL",
  "SEAL",
  "RING",
  "COVER",
  "COVER",
  "HEAD-CYL",
  "CHAIN-RIVET",
  "CHAIN",
  "KIT",
  "KIT",
  "NUT",
  "DIPSTICK",
  "BREATHER",
  "TUBE",
  "ROD END",
  "ROD END",
  "LEVEL GLASS",
  "LEVEL GLASS",
  "LEVEL GLASS",
  "BUSHING",
  "KNOB",
  "KNOB",
  "RING",
  "BALL",
  "BALL",
  "VALVE",
  "VALVE",
  "VALVE",
  "STRAINER",
  "LOCK",
  "LOCK",
  "LOCK",
  "CAPSCREW",
  "CAPSCREW",
  "CAPSCREW",
  "SEAL",
  "SEAL",
  "SEAL",
  "BEARING",
  "BEARING",
  "BEARING",
  "GEAR",
  "BEARING",
  "BEARING",
  "BEARING",
  "BEARING",
  "BEARING",
  "BEARING",
  "BEARING",
  "SPACER",
  "SPACER",
  "SPACER",
  "KIT-SNAPRING",
  "KIT-SNAPRING",
  "KIT-SNAPRING",
  "GEAR",
  "DRUM",
  "DRUM",
  "SHIM",
  "SHIM",
  "SHIM",
  "SHIM",
  "SHIM",
  "SHIM",
  "SHIM",
  "SHIM",
  "COVER",
  "COVER",
  "GEAR",
  "CUP",
  "CUP",
  "SPRING",
  "SPRING",
  "SPRING",
  "DRUM",
  "DRUM",
  "O-RING        VITON",
  "O-RING        VITON",
  "O-RING",
  "O-RING",
  "SEAL",
  "SEAL",
  "KIT",
  "KIT",
  "KIT",
  "KIT",
  "CYLINDER",
  "CYLINDER",
  "SWIVEL",
  "WAGNER PART",
  "BREATHER",
  "BREATHER",
  "JOINER        SWIVEL",
  "CORDGRIP",
  "CORDGRIP",
  "CORDGRIP",
  "WASHER",
  "DRIVELINE",
  "DRIVELINE",
  "DRIVELINE",
  "YOKE",
  "WAGNER PART",
  "TUBE",
  "TUBE",
  "FITTING",
  "FITTING",
  "SWITCH",
  "SWITCH",
  "RING",
  "RING",
  "PACKING SEAL",
  "PACKING SEAL",
  "WIPER",
  "RETAINER",
  "RETAINER",
  "BEARING",
  "BEARING",
  "GASKET",
  "GASKET",
  "PLATE",
  "ACTUATOR",
  "ACTUATOR",
  "SWITCH",
  "CLUTCH ASSY.",
  "CLUTCH ASSY.",
  "BOLT",
  "RING",
  "RING",
  "RING",
  "CABLE LUG",
  "SHEAVE",
  "RING",
  "O-RING",
  "PLUG",
  "O-RING",
  "VALVE",
  "BOLT",
  "TRUNNION",
  "ADAPTER",
  "VALVE",
  "CAPSCREW",
  "BRAKE ASSY",
  "RUBBER BOOT",
  "SPRING",
  "FILTER",
  "CAP",
  "LUBRICATOR",
  "CLAMP",
  "CLAMP",
  "HOUSING",
  "BEARING",
  "SEAL",
  "DIODE",
  "BOLT",
  "LOCK NUT",
  "NUT",
  "NUT",
  "WASHER",
  "FAN",
  "SLEEVE",
  "PUMP",
  "RETAINER",
  "SEAL",
  "O-RING        VITON",
  "LOCK NUT",
  "LOCK NUT",
  "BAFFLE PLATE",
  "BAFFLE PLATE",
  "STUD",
  "STUD",
  "STUD",
  "STOP BLOCK",
  "STOP BLOCK",
  "PIN",
  "PIN",
  "PISTON RING",
  "PISTON RING",
  "PISTON RING",
  "PISTON RING",
  "PISTON RING",
  "PISTON RING",
  "PLUG",
  "HUB-FAN",
  "SEAL",
  "MOUNT",
  "MOUNT",
  "KIT",
  "KIT",
  "WASHER",
  "GEAR",
  "SPOOL",
  "SPACER",
  "SPACER",
  "AIR CLEANER",
  "HOSE",
  "HOSE",
  "REDUCER",
  "REDUCER",
  "CLAMP",
  "CLAMP",
  "RETAINER",
  "SCREW",
  "GLOW PLUG",
  "DRIVER",
  "NUT",
  "NUT",
  "SEAL",
  "SEAL",
  "BEARING",
  "SHAFT",
  "CUP",
  "SEAT",
  "BOOT",
  "CUP",
  "SPRING",
  "SPRING",
  "SPRING",
  "VALVE",
  "VALVE",
  "CONNECTOR",
  "LOCKWASHER",
  "CYLINDER",
  "O-RING",
  "SPRING",
  "SPRING",
  "CLEANER",
  "BODY",
  "GASKET",
  "GASKET",
  "NUT",
  "NUT",
  "PIN",
  "LUBRICATOR",
  "O-RING",
  "O-RING",
  "KIT",
  "KIT",
  "SEAL KIT",
  "SEAL KIT",
  "SPACER",
  "COVER",
  "TUBE",
  "TUBE",
  "SHAFT",
  "SHAFT",
  "COVER",
  "COVER",
  "TUBE",
  "TUBE",
  "TUBE",
  "CLIPPINGS",
  "RIVET",
  "PLATE",
  "PLATE",
  "SHAFT",
  "SHAFT",
  "ADAPTOR",
  "ADAPTOR",
  "PIN",
  "PIN",
  "PIN",
  "PLATE",
  "PLATE",
  "HOUSING",
  "HOUSING",
  "CAP",
  "CAP",
  "BOLT",
  "BOLT",
  "BOLT",
  "BOLT",
  "WASHER",
  "WASHER",
  "WASHER",
  "SHAFT",
  "SHAFT",
  "SHAFT",
  "SHAFT",
  "PLUG",
  "PLUG",
  "SCREW",
  "SCREW",
  "PLUG",
  "PLUG",
  "SCREW",
  "SCREW",
  "SCREW",
  "CUSHION",
  "CUSHION",
  "BACK PART",
  "BACK PART",
  "BALL",
  "PLATE-NAME",
  "HANDLE",
  "HUB-HANDLE",
  "WASHER",
  "DETENT",
  "PLUNGER",
  "WAGNER PART",
  "FITTING",
  "RECEP CONNECTOR",
  "RECEP CONNECTOR",
  "RECEP CONNECTOR",
  "LOCK WASHER",
  "LOCK WASHER",
  "NUT",
  "NUT",
  "PLUG",
  "PLUG",
  "GEAR",
  "WAGNER PART",
  "WAGNER PART",
  "SEAL",
  "SEAL",
  "SCREW",
  "WASHER",
  "BUSHING",
  "WASHER",
  "ROD",
  "SPRING",
  "SPOOL",
  "YOKE",
  "SPRING",
  "RING",
  "BALL",
  "O-RING",
  "NUT",
  "HORN",
  "HORN",
  "CARRIER",
  "BOLT",
  "KIT-PINION",
  "SHIM",
  "SHIM",
  "SHIM",
  "HOSE ASSEMBLY",
  "HOSE ASSEMBLY",
  "HUMP HOSE",
  "LOCKNUT",
  "WASHER",
  "VALVE",
  "VALVE",
  "KIT",
  "GASKET",
  "BEARING",
  "SPACER",
  "SPACER",
  "SHAFT",
  "SHAFT",
  "CAP",
  "CAP",
  "CAP",
  "SPACER",
  "SPACER",
  "SPACER",
  "DEFLECTOR",
  "CLAMP",
  "PLATE",
  "PLATE",
  "PISTON",
  "BEARING PART",
  "SNAP RING",
  "BEARING",
  "EXHAUST DEFLECT",
  "WASHER",
  "WASHER",
  "VALVE",
  "VALVE",
  "VALVE",
  "HOUSING",
  "HOUSING",
  "HOUSING",
  "PIN",
  "PIN",
  "PIN",
  "VALVE",
  "VALVE",
  "VALVE",
  "VALVE",
  "VALVE",
  "VALVE",
  "VALVE",
  "VALVE",
  "PLUG",
  "PLUG",
  "HOUSING",
  "HOUSING",
  "PIN",
  "PIN",
  "RING",
  "RING",
  "RING",
  "SLEEVE",
  "SLEEVE",
  "PLUGG",
  "PLUGG",
  "GUIDE",
  "GUIDE",
  "PISTON",
  "PISTON",
  "STOP",
  "STOP",
  "VALVE",
  "SPOOL VALVE",
  "SEAT",
  "SEAT",
  "SEAT",
  "SPACER",
  "SPACER",
  "PLATE",
  "PLATE",
  "BALL",
  "BALL",
  "BALL",
  "TUBE",
  "BALL",
  "BALL",
  "NUT",
  "NUT",
  "NUT",
  "SUPPORT",
  "SUPPORT",
  "TUBE",
  "TUBE",
  "DIP STICK",
  "DIP STICK",
  "SHAFT",
  "SHIELD",
  "RING",
  "SPACER",
  "PIN",
  "PIN",
  "PIN",
  "SPACER",
  "SPACER",
  "SPACER",
  "SPACER",
  "GASKET",
  "GASKET",
  "GASKET",
  "PIN",
  "PIN",
  "SPACER",
  "SPACER",
  "GEAR",
  "GEAR",
  "PLATE",
  "SCREEN",
  "SCREEN",
  "FLANGE",
  "FLANGE",
  "FLANGE",
  "CAP",
  "PLATE",
  "GUARD",
  "CYLINDER",
  "SPRING",
  "REPAIR KIT",
  "FUSE",
  "HOLDER",
  "GROMMET",
  "GROMMET",
  "SCREW",
  "YOKE",
  "ROD END",
  "ROD END",
  "ROD END",
  "LEAD",
  "FITTING",
  "AIR TANK",
  "CONE",
  "CONE",
  "SCREW",
  "CLEVIS",
  "CABLE GLAND",
  "CABLE GLAND",
  "PULLEY",
  "HOUSING",
  "HOUSING",
  "HOUSING",
  "PIN",
  "WAGNER PART",
  "RECEPTACLE     PYLE NATIONAL",
  "TERM RING",
  "TERM RING",
  "STEERING WHEEL",
  "STEERING WHEEL",
  "BUSHING",
  "GASKET",
  "KIT",
  "ROD END",
  "ROD END",
  "CONTROLER",
  "CONTROLER",
  "CONTROLER",
  "QUAD-RING",
  "QUAD-RING",
  "SWITCH-ARM",
  "CORDGRIP",
  "NUT",
  "NUT",
  "PLUG",
  "BACKUP RING",
  "SPRING",
  "NIPPLE",
  "WAGNER PART",
  "SPLICE-LINE",
  "TERM RING",
  "TERM RING",
  "FLANGE BEARING",
  "DETAILS",
  "DETAILS",
  "SCREW",
  "SCREW",
  "WAGNER PART",
  "NUT",
  "NUT",
  "WASHER",
  "WASHER",
  "WASHER",
  "SCREW",
  "SCREW",
  "CAP",
  "CAP",
  "STUD",
  "STUD",
  "STUD",
  "PUMP",
  "CAPSCREW",
  "CAPSCREW",
  "CAPSCREW",
  "CONNECTOR",
  "O-RING        VITON",
  "O-RING        VITON",
  "MUFFLER",
  "SPRING",
  "PAINT-YEL    SPRAY   12.25 OZ",
  "FAN",
  "BALL",
  "BELT",
  "BELT -SINGLE",
  "COMPRESSOR",
  "CLEVIS",
  "CLEVIS",
  "WAGNER PART",
  "WAGNER PART",
  "SCREW",
  "PUSH ROD",
  "SPRING",
  "SWITCH",
  "SWITCH",
  "ELBOW",
  "BEARING",
  "BUSHING",
  "BUSHING",
  "SEAT BACK",
  "STARTER",
  "CLAMP",
  "CLAMP",
  "COVER",
  "DIAPHRAM",
  "PLATE",
  "PLUNGER",
  "HOSE",
  "CLAMP",
  "CLAMP",
  "WASHER",
  "ADAPTOR      FLANGE",
  "O-RING-VITON",
  "O-RING-VITON",
  "O-RING-VITON",
  "KIT-OIL SEAL",
  "STRAINER PL",
  "MOUNTING PLATE",
  "MOUNTING PLATE",
  "MOUNTING PLATE",
  "COUPLING",
  "COUPLING",
  "DIFF.KIT",
  "FITTING",
  "FITTING",
  "HOOD SUPPORT",
  "HOOD SUPPORT",
  "HOOD SUPPORT",
  "ADAPTER-RH",
  "ADAPTER-LH",
  "BRKT-MT",
  "HOSE ASSY",
  "CLAMP-LUG",
  "CAPSCREW",
  "RING/CLUTCH     HOLD OUT",
  "CLAMP",
  "CLAMP",
  "CLAMP",
  "SNAP RING",
  "SNAP RING",
  "STATOR",
  "STATOR",
  "COIL",
  "COIL",
  "SUPPORT",
  "MASTER CYL",
  "PUMP",
  "PUMP",
  "PLUG",
  "NUT",
  "FERRULE",
  "NUT",
  "FERRULE",
  "FITTING",
  "RING",
  "VALVE",
  "VALVE",
  "SCREEN",
  "SCREW",
  "PLUG",
  "LOCKWASHER",
  "O-RING",
  "CYLINDER BLOCK",
  "RETAINER",
  "SOCKET",
  "CABLE LUG",
  "CABLE LUG",
  "CABLE LUG",
  "CABLE LUG",
  "CABLE LUG",
  "CABLE LUG",
  "CABLE LUG",
  "CABLE LUG",
  "CABLE LUG",
  "CABLE LUG",
  "CABLE LUG",
  "CABLE LUG",
  "CABLE LUG",
  "SEALING PLUG",
  "SEALING PLUG",
  "SEALING PLUG",
  "SEALING PLUG",
  "TERM RING",
  "TERM RING",
  "GROMMET",
  "CABLE LUG",
  "CABLE LUG",
  "CABLE LUG",
  "CABLE LUG",
  "RECEPTACLE",
  "RECEPTACLE",
  "RECEPTACLE",
  "CABLE LUG",
  "CABLE LUG",
  "V-BELT",
  "V-BELT",
  "PULLEY",
  "TERM RING",
  "TERM RING",
  "TERM RING",
  "CABLE LUG",
  "CABLE LUG",
  "CABLE LUG",
  "CABLE LUG",
  "CABLE LUG",
  "CONVERTER    ASSY",
  "SHAFT",
  "SHAFT",
  "PLUG",
  "PLUG",
  "PUMP",
  "PUMP",
  "FLTR ELEMENT",
  "SPRING",
  "SPRING",
  "KNOB-RED",
  "READOUT ASSY",
  "BASE-READOUT",
  "SENSOR",
  "CONNECTOR    -DETECTOR",
  "INJECTOR",
  "INJECTOR",
  "ELEMENT-PRMR",
  "STUD",
  "STUD",
  "RECEP CONNECTOR",
  "RECEP CONNECTOR",
  "NUT",
  "NUT",
  "RECEPTACLE",
  "RECEPTACLE",
  "PLUG",
  "PLUG",
  "HOSE",
  "HOSE",
  "HOSE(50FT)               -BULK",
  "DRUM",
  "BRAKE",
  "BRAKE",
  "RECEP CONNECTOR",
  "RECEP CONNECTOR",
  "WAGNER PART",
  "O-RING",
  "GRIP",
  "HOSE",
  "PIN",
  "ADAPTER",
  "GAUGE",
  "GAUGE",
  "GAUGE",
  "PRESSURE SWITCH",
  "PRESSURE SWITCH",
  "LOCK WASHER",
  "LOCK WASHER",
  "FUSE",
  "RECEPTACLE",
  "RECEPTACLE",
  "HOUSING-RED",
  "CONTACT30AMP",
  "DRIVE ASSY",
  "REPAIR KIT",
  "REPAIR KIT",
  "REPAIR KIT",
  "KIT",
  "SCREW",
  "SEAL",
  "SWIVEL",
  "SWIVEL",
  "DIFF/CARRIER",
  "GASKET",
  "NUT",
  "FAN",
  "MOUNT",
  "ALTERNATOR",
  "VALVE",
  "VALVE",
  "GASKET",
  "RING",
  "RETAINER",
  "BOLT",
  "PLUNGER",
  "BOLT",
  "COVER",
  "SHIM",
  "WAGNER PART",
  "ELBOW 90 DEG",
  "SPRING",
  "RETAINER",
  "BRG",
  "SHAFT",
  "SHAFT",
  "LINK-DRIVE",
  "SET-ROTOR",
  "FITTING",
  "FITTING",
  "FITTING",
  "C/U 359466",
  "KIT-REPAIR",
  "PLUG",
  "CABLE LUG",
  "CABLE LUG",
  "TERM RING",
  "TERM RING",
  "TERM RING",
  "TERM RING",
  "CLAMP",
  "BULKHEAD CONN.",
  "SNAP RING",
  "PISTON",
  "O-RING",
  "PLNGR-RELIEF",
  "POPPET",
  "COIL",
  "EXT VALVE STEM",
  "EXT VALVE STEM",
  "EXT VALVE STEM",
  "VALVE",
  "VALVE",
  "VALVE",
  "VALVE",
  "VALVE",
  "ELEMENT",
  "ELEMENT",
  "HOSE, BULK",
  "HOSE ASSY",
  "INDICATOR",
  "BOARD-TERMNL",
  "CABLE LUG",
  "TERM RING",
  "CLAMP",
  "CLAMP",
  "BEARING",
  "BEARING",
  "BEARING",
  "VALVE",
  "VALVE",
  "SPRING PIN",
  "GASKET",
  "CABLE LUG",
  "CABLE LUG",
  "CABLE LUG",
  "HOSE ASSY",
  "NUT",
  "NUT",
  "NUT",
  "NUT",
  "OIL PLUG",
  "WAGNER PART",
  "PRESSURE SWITCH",
  "PRESSURE SWITCH",
  "PRESSURE SWITCH",
  "RING BACK UP",
  "WAGNER PART",
  "WAGNER PART",
  "COVER",
  "SPACER",
  "SPACER",
  "VALVE",
  "SHELL",
  "GAUGE",
  "GAUGE",
  "GAUGE",
  "CHECK VALVE",
  "SOLENOID ASY",
  "SCREW, HEX HEAD",
  "SCREW, HEX HEAD",
  "SCREW, HEX HEAD",
  "SCREW, HEX HEAD",
  "SEAL",
  "RING",
  "WASHER",
  "FITTING",
  "NUT",
  "WASHER",
  "CAPSCREW",
  "GASKET",
  "GASKET",
  "BOLT",
  "BOLT",
  "NUT",
  "IMPELLER",
  "PIN",
  "BOLT",
  "PLUG",
  "WASHER",
  "WASHER",
  "SEAL",
  "SCREW, HEX HEAD",
  "BOLT",
  "BOLT",
  "BOLT",
  "ADAPTER                -WRENCH",
  "SCREW, HEX HEAD",
  "SCREW, HEX HEAD",
  "LOCKWASHER",
  "HOUSING",
  "HOUSING",
  "WAGNER PART",
  "WAGNER PART",
  "PULLEY",
  "SPACER",
  "SPACER",
  "SPACER",
  "CAPSCREW",
  "CAPSCREW",
  "LENS AMBER",
  "SWITCH",
  "WAGNER PART",
  "WAGNER PART",
  "CABLE LUG",
  "CABLE LUG",
  "PLUG",
  "ROD END",
  "ROD END",
  "ROD END",
  "ROD END",
  "END ROD",
  "END-ROD",
  "FILTER",
  "BAR",
  "STEM",
  "LOCKWASHER",
  "ADAPTER ASSY",
  "ADAPTER ASSY",
  "BOLT",
  "WAGNER PART",
  "WAGNER PART",
  "BUSHING",
  "BUSHING",
  "BODY",
  "FILTER",
  "GAUGE",
  "ACCUMULATOR",
  "VALVE",
  "CRANK",
  "BALL",
  "O-RING",
  "O-RING",
  "O-RING",
  "O-RING",
  "RING-BACKUP",
  "O-RING      (PKG OF 5)",
  "O-RING",
  "VALVE",
  "BUSHING",
  "HANDLE",
  "HANDLE",
  "LINK",
  "SEAT",
  "CLEVIS PIN",
  "RING-BACKUP",
  "RING-BACKUP",
  "O-RING",
  "RING-BACKUP",
  "RETAINER RING",
  "RETAINING RING",
  "CHECK VALVE",
  "KIT",
  "BEARING",
  "O-RING",
  "PISTON",
  "PLUNGER",
  "SEAL",
  "WAGNER PART",
  "BULB",
  "BULB",
  "ELEMENT",
  "SPRING(PKG5)",
  "PLATE-RET",
  "BARREL",
  "MOTOR          STARTER",
  "KEY",
  "PISTON",
  "RING         RETAINING",
  "SPRING",
  "WIPER RING",
  "SEAL",
  "SEAL",
  "BACKUP RING",
  "ADJUSTING NUT",
  "ADJUSTING NUT",
  "ADJUSTING NUT",
  "LOCK-TAB",
  "BOLT",
  "CLIP",
  "LOCK-TAB",
  "SEAL",
  "SEAL",
  "BOLT",
  "BOLT",
  "BOLT",
  "BOLT",
  "PIPE",
  "DIRECTOR",
  "PLUG",
  "PLUG",
  "PLUG",
  "HOSE ASSY",
  "DRUM",
  "DRUM",
  "BUSHING",
  "RETAINER",
  "RETAINER",
  "PIN",
  "HUB & CUP",
  "NUT",
  "WAGNER PART",
  "DOWEL-TAPERD",
  "SHAFT",
  "CARRIER&CAP  ASSY",
  "CAP SCREW",
  "CONE-BRG",
  "CONE",
  "SEAL",
  "COVER ASSY",
  "YOKE"
];

const synonyms = [
  { master: "radial shaft seal", synonym: "lip seal" },
  { master: "motor", synonym: "engine" }
];

const specialWords = ["o-ring", "v ring", "v-ring"];

const abbreviations = [
  { abbreviation: "ASSY", expansion: "ASSEMBLY" },
  { abbreviation: "ASSY.", expansion: "ASSEMBLY" },
  { abbreviation: "ASY", expansion: "ASSEMBLY" },
  { abbreviation: "ASSY.", expansion: "ASSEMBLY" },
  { abbreviation: "BEAR.", expansion: "BEARING" },
  { abbreviation: "BRK", expansion: "BREAK" },
  { abbreviation: "TERMNL", expansion: "TERMINAL" },
  { abbreviation: "BRG", expansion: "BEARING" },
  { abbreviation: "ATTACH.", expansion: "ATTACHMENT" },
  { abbreviation: "BRKT", expansion: "BRAKET" },
  { abbreviation: "CORDGRIP", expansion: "CORD GRIP" },
  { abbreviation: "COMPL.", expansion: "COMPLETE" },
  { abbreviation: "CAPSCREW", expansion: "CAP SCREW" },
  { abbreviation: "CPLG", expansion: "COUPLING" },
  { abbreviation: "CYL", expansion: "CYLINDER" },
  { abbreviation: "CYL.", expansion: "CYLINDER" },
  { abbreviation: "CYLIND", expansion: "CYLINDER" },
  { abbreviation: "CYLIND.", expansion: "CYLINDER" },
  { abbreviation: "CYLINDE", expansion: "CYLINDER" },
  { abbreviation: "FILT.", expansion: "FILTER" },
  { abbreviation: "FRICT.", expansion: "FRICTION" },
  { abbreviation: "HD", expansion: "HEAD" },
  { abbreviation: "HD.", expansion: "HEAD" },
  { abbreviation: "CART.", expansion: "CARTRIDGE" },
  { abbreviation: "CARTR.", expansion: "CARTRIDGE" },
  { abbreviation: "HYD.", expansion: "HYDRAULIC" },
  { abbreviation: "HYDR.", expansion: "HYDRAULIC" },
  { abbreviation: "REDUC.", expansion: "REDUCER" },
  { abbreviation: "REGUL.", expansion: "REGULATOR" },
  { abbreviation: "FLG", expansion: "FLANGE" }
];

const _stringSplit = stringToSplit => {
  // check if the delimiter is a comma (the string most likely starts with a NOUN)
  if (stringToSplit.indexOf(",") >= 0) {
    return stringToSplit.replace(",", " ").toUpperCase();
    // check if the delimiter is a semicolon (the string most likely starts with a NOUN)
  } else if (stringToSplit.indexOf(";") >= 0) {
    return stringToSplit.replace(";", " ").toUpperCase();
  } else {
    // The string most likely ends with a NOUN
    return stringToSplit.toUpperCase().split(" ");
  }
};

const _findAbbreviations = (string, abbreviationsArray) => {
  const stringArray = _stringSplit(string);

  const abbreviationMatches = [];
  abbreviationsArray.forEach(item => {
    if (stringArray.indexOf(item.abbreviation) >= 0) {
      abbreviationMatches.push({
        abbreviation: item.abbreviation.toUpperCase(),
        expansion: item.expansion.toUpperCase()
      });
    }
  });
  return abbreviationMatches;
};

const _replaceAbbreviations = (string, abbreviationsArray) => {
  if (_findAbbreviations.length > 0) {
    const abbreviationMatches = _findAbbreviations(string, abbreviationsArray);
    let newString = string.toUpperCase();
    abbreviationMatches.forEach(item => {
      item.abbreviation[item.abbreviation.length - 1] === "."
        ? (abb = item.abbreviation.replace(/.$/, "\\."))
        : (abb = item.abbreviation);
      re = new RegExp(abb);
      newString = newString.replace(re, item.expansion);
    });
    return newString;
  } else {
    return string;
  }
};

const _regexString = (string, abbreviationsArray) => {
  const filterPattern1 = /[^a-zA-Z;,.]+/g; // find all non English alphabetic characters.
  const filterPattern2 = /\b\w{1,2}\b/g; // find words that are less then three characters long.
  const filterPattern4 = /\s\s+/g; // find multiple whitespace, tabs, newlines, etc.
  const filterPattern3 = /(,|\.)\s*$/;
  const filteredString = _replaceAbbreviations(string, abbreviationsArray)
    .toUpperCase()
    .replace(filterPattern1, " ")
    .replace(filterPattern2, match => {
      let abbr = abbreviationsArray.find(x => x.abbreviation === match);
      return abbr ? abbr.expansion : "";
    })
    .replace(filterPattern3, "")
    .replace(filterPattern4, " ")
    .trim(); // remove leading and trailing whitespace.
  return filteredString;
};

const stringOrganizer = (stringArray, abbreviationsArray) => {
  const newStringArray = [];
  const nounsArray = [];

  const addNounToArray = noun => {
    const i = noun.indexOf(",");
    const firstTerm = i === -1 ? noun : noun.substring(0, i);

    if (nounsArray.indexOf(firstTerm) === -1) {
      nounsArray.push(firstTerm);
    }
  };

  const _delimiterFixer = (delimiter, string, abbreviationsArray) => {
    // exist a comma in the string
    const cleanedString = _regexString(string, abbreviations);
    const textAfterDelimiter = cleanedString
      .substring(cleanedString.indexOf(delimiter) + 1)
      .trim();
    const textBeforeDelimiter = cleanedString
      .replace(textAfterDelimiter, "")
      .replace(delimiter, "")
      .trim();
    const newString = textAfterDelimiter.length
      ? `${textBeforeDelimiter}, ${textAfterDelimiter
          .replace(/(,|\.)\s*$/, "")
          .trim()}`
      : textBeforeDelimiter.replace(/,\s*$/, "");
    newStringArray.push(newString);
    addNounToArray(newString);
  };
  // const fixedStrings = [];
  stringArray.forEach(string => {
    if (_regexString(string, abbreviations).indexOf(",") >= 0) {
      // exist a comma in the string
      _delimiterFixer(",", string);
    } else if (_regexString(string, abbreviations).indexOf(";") >= 0) {
      // exist a semicolon in the string
      _delimiterFixer(";", string);
    } else if (_regexString(string, abbreviations).indexOf(".") >= 0) {
      _delimiterFixer(".", string);
    } else if (string.trim().indexOf(" ") >= 0) {
      // exist only space(s) in the string;
      const cleanedString = _regexString(string, abbreviations);
      if (cleanedString.length > 0) {
        const noun = cleanedString.match(/\b(\w+)$/g).join(""); // \b(\w+)$ find last word in the string (the noun in this case).

        const textBeforeDelimiter = cleanedString.replace(noun, "").trim();
        const newString = noun.length
          ? `${noun}, ${textBeforeDelimiter}`.replace(/,\s*$/, "")
          : noun.replace(/,\s*$/, "");
        newStringArray.push(newString);
        addNounToArray(newString);
      } else {
        newStringArray.push("This part has some issues!");
      }
    } else {
      const newString = _regexString(string, abbreviations);
      newStringArray.push(newString.replace(/,\s*$/, ""));
      addNounToArray(newString);
    }
    /*
    fixedStrings.push({
      oldString: string,
      newString: regStr.join(" "),
      noun:
        string.indexOf(",") >= 0 || string.indexOf(";") >= 0
          ? regStr[0]
          : regStr[regStr.length - 1]
    }); */
  });
  //return fixedStrings;
  return [newStringArray.sort(), nounsArray.sort()];
};

console.log(stringOrganizer(strings, abbreviations)[0]);
console.log(stringOrganizer(strings, abbreviations)[1]);

/* console.time("Hello");
console.log(regexString(testStringOriginal, abbreviations));
console.timeEnd("Hello"); */
/* function partOfSpeech(document) {
  let obj = {};
  obj.nouns = document
    .terms()
    .nouns()
    .data();

  console.log("nouns", document.nouns().out("array"));
  console.log("values: ", document.values().out("array"));
  console.log("verbs: ", document.verbs().out("array"));
  console.log("adjectives: ", document.adjectives().out("array"));
  console.log(testStringOriginal);
}

// partOfSpeech(doc) */
